### PR TITLE
added my project

### PR DESCRIPTION
**Pull request by RedFred7**

### CODE REVIEW

**Comment by rrrene** [comment]
Hi there,

the inch-pages project was discontinued a year ago, but there is the successor Inch CI: [Inline docs](http://inch-ci.org/github/bodleian/datacite_mds) (on this page you can get your badge)

**Comment by rrrene** [comment]
@RedFred7 if you have any problems with the "new" site and badge, please let me know! I'm happy to help.

Will close this PR for now :+1:

**Comment by RedFred7** [comment]
Hi @rrrene, I get an error when i try to visit https://inch-ci.org/github/bodleian/datacite_mds, so I can't get my badge. I'm not sure if there's some metadata I need to update first or what. Any ideas ?

Thanks.

**Comment by rrrene** [comment]
So, just to be clear, you do not get this webpage?

image

**Comment by RedFred7** [comment]
sorry, yes I get this page. Where do I go from here?

**Comment by rrrene** [comment]
You have to click on the badge to get one (like on Travis). ... Mmh, maybe I should make this more clear ...

**Comment by RedFred7** [comment]
Ahhhhh! got it now, thank you!

**Pull request closed without merging**
